### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Hammarn** [ewels/MultiQC_NGI#16]
```
[INFO   ]      ngi_rnaseq : Found 1 heatmaps
[ERROR  ]         multiqc : Oops! The 'ngi_rnaseq' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
```

``` python
============================================================
Module ngi_rnaseq raised an exception: Traceback (most recent call last):
  File "/pica/h1/richam/MultiQC/scripts/multiqc", line 345, in multiqc
    report.modules_output.append(mod())
  File "/pica/h1/richam/MultiQC_NGI/multiqc_ngi/modules/ngi_rnaseq/ngi_rnaseq.py", line 39, in __init__
    n['mds_plot'] = mds_plot.parse_reports(self)
  File "/pica/h1/richam/MultiQC_NGI/multiqc_ngi/modules/ngi_rnaseq/mds_plot.py", line 43, in parse_reports
    data[s[0]] = [{'x': float(s[1]), 'y': float(s[2])}]
ValueError: could not convert string to float: logFC
=========================================================
```

Included the offending file:
[edgeR_MDS_plot_coordinates.txt](https://github.com/ewels/MultiQC_NGI/files/519751/edgeR_MDS_plot_coordinates.txt)

**Comment by Hammarn** [comment]
Bumping this instead of creating a new issue @ewels
