### ISSUE TITLE
Error running multiqc on IRMA/funk006/NGI

### ISSUE THREAD

**Issue by parlundin** [ewels/MultiQC_NGI#9]
```python
Traceback (most recent call last):
  File "/lupus/ngi/sw/anaconda/envs/NGI/bin/multiqc", line 460, in <module>
    multiqc()
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/lupus/ngi/sw/anaconda/envs/NGI/bin/multiqc", line 334, in multiqc
    plugin_hooks.mqc_trigger('after_modules')
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/multiqc/utils/plugin_hooks.py", line 21, in mqc_trigger
    hook()
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/multiqc_ngi/multiqc_ngi.py", line 62, in __init__
    self.general_stats_sample_meta()
  File "/lupus/ngi/sw/anaconda/envs/NGI/lib/python2.7/site-packages/multiqc_ngi/multiqc_ngi.py", line 247, in general_stats_sample_meta
    amounts = [gsdata[x]['amount_taken'] for x in gsdata]
KeyError: 'amount_taken'
```

**Comment by ewels** [comment]
Fixed in 1b728935ae9b26054e533a3c7afc680bed8deca8
